### ISSUE TITLE
No spaces allowed in signal _property

### ISSUE THREAD

**Issue by rob-yerc** [amphoradata/python-sdk#7]
When creating a signal data transfer object, the string for _property cannot contain spaces.  Here is an example:
>>> newsignal = ac.Signal(_property='Sensor Temperature', value_type='Numeric')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/amphora_client/models/signal.py", line 62, in __init__
    self._property = _property
  File "/usr/local/lib/python3.7/site-packages/amphora_client/models/signal.py", line 107, in _property
    raise ValueError(r"Invalid value for `_property`, must be a follow pattern or equal to `/^[a-zA-Z_]{3,20}$/`")  # noqa: E501
ValueError: Invalid value for `_property`, must be a follow pattern or equal to `/^[a-zA-Z_]{3,20}$/`

If I remove the  space it works:
>>> newsignal = ac.Signal(_property='SensorTemperature', value_type='Numeric')

However, the web ui allows spaces in the name when creating a new signal.  Currently we have several timeseries with spaces in the name so I would like to know what is the long term direction, i.e. do I need to remove spaces from my signal names?

**Comment by xtellurian** [comment]
Hey @rob-yerc 

Thanks for reporting this behaviour!

The Python SDK is indeed correct - property names should match the following regex specification:

`^[a-zA-Z_]{3,20}$`

The UI is not correctly validating the name, which is incorrect behaviour. We're fixing this in v0.7.4

**Comment by xtellurian** [comment]
0.7.4 has been released, and this should now be resolved.

**Comment by xtellurian** [comment]
There seems to be an issue with properties that start with a capital letter not being serialised correctly. To ensure consistency across all properties, we're going to update the regex for property names to the following, meaning you must start the property name with a lowercase letter:

`^[a-z][a-zA-Z_]{3,20}$`
